### ISSUE TITLE
the link of the document is broken

### ISSUE THREAD

**Issue by cwenan** [vuepress/vuepress-plugin-blog#116]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [ ] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### Other relevant information

- `npx vuepress info`:

**Comment by cwenan** [comment]
just it

**Comment by billyyyyy3320** [comment]
Thanks. Check https://vuepress-plugin-blog.billyyyyy3320.com/.
