### ISSUE TITLE
vuepress-plugin-blog doc site was broken

### ISSUE THREAD

**Issue by FrankFan** [vuepress/vuepress-plugin-blog#117]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

visit url [https://vuepress-plugin-blog.ulivz.com/guide/getting-started.html](https://vuepress-plugin-blog.ulivz.com/guide/getting-started.html)

![image](https://user-images.githubusercontent.com/1589433/126427901-b0266869-76f2-4915-9518-e26d30bf8266.png)

I'm sure there's nothing wrong with my network

**Comment by iswsg** [comment]
I also met this issue

**Comment by Void-7** [comment]
same

**Comment by billyyyyy3320** [comment]
Thanks. Check https://vuepress-plugin-blog.billyyyyy3320.com/.
