### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by adriatic** [vuepress/vuepress-plugin-blog#87]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x ] This issue doesn't need a reproduction repro, here is the steps to reproduce

![image](https://user-images.githubusercontent.com/2712405/98277983-f5be9d00-1f65-11eb-9a2f-805435507909.png)

#### Other relevant information

- `npx vuepress info`:

**Comment by billyyyyy3320** [comment]
Cannot load your image.

**Comment by Kocal** [comment]
It's written `Offical blog` instead of `Official blog`, but a PR would be welcome instead of an issue...

**Comment by adriatic** [comment]
@Kocal says `it would have been better to create a PR instead of an issue :(`

It would be even better to send $50 to support the developer. I am guided by this reasoning: PRs are meaningless in the context of warning about a trivial issue because the maintainer is a lot better off to fix it in hos development branch than to verify the correctness of my PR (as well as it easier for the person reporting the spelling error).

@billyyyyy3320 says `cannot load your image` - please look at the [original report](https://github.com/vuepress/vuepress-plugin-blog/issues/87#issue-737145493). My image is there visible to anyone.

**Comment by billyyyyy3320** [comment]
Either fixing an issue or reporting one is making it better. Thanks for both of you.

**Comment by adriatic** [comment]
@billyyyyy3320 - thank you for your words 😄
